services:
  postgres:
    container_name: dreik-postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./.database/avatars:./.database/avatars
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
