basePath: /api
definitions:
  requestbody.ConfirmAccount:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  requestbody.CreateAccount:
    properties:
      email:
        maxLength: 254
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
      username:
        maxLength: 32
        minLength: 5
        type: string
    required:
    - email
    - password
    - username
    type: object
  requestbody.CreateSession:
    properties:
      login:
        maxLength: 254
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  requestbody.CreateWorkout:
    properties:
      date:
        type: string
      duration:
        type: integer
      kind:
        type: string
    required:
    - date
    - duration
    - kind
    type: object
  requestbody.ResetPassword:
    properties:
      email:
        maxLength: 254
        type: string
    required:
    - email
    type: object
  requestbody.UpdateAccount:
    properties:
      display_name:
        maxLength: 50
        minLength: 1
        type: string
      is_private:
        type: boolean
      password:
        maxLength: 64
        minLength: 8
        type: string
      username:
        maxLength: 32
        minLength: 5
        type: string
    type: object
  requestbody.UpdatePassword:
    properties:
      password:
        maxLength: 64
        minLength: 8
        type: string
      token:
        type: string
    required:
    - password
    - token
    type: object
  responsebody.Account:
    properties:
      avatar_url:
        type: string
      created_at:
        type: string
      display_name:
        type: string
      email:
        type: string
      id:
        type: string
      is_confirmed:
        type: boolean
      is_private:
        type: boolean
      username:
        type: string
    type: object
  responsebody.ActivityHistory:
    properties:
      count:
        type: integer
      user_id:
        type: string
      workouts:
        items:
          $ref: '#/definitions/responsebody.Workout'
        type: array
    type: object
  responsebody.Message:
    properties:
      message:
        type: string
    type: object
  responsebody.Profile:
    properties:
      avatar_url:
        type: string
      display_name:
        type: string
      id:
        type: string
      is_private:
        type: boolean
      username:
        type: string
      week_activity:
        items:
          $ref: '#/definitions/responsebody.Workout'
        type: array
    type: object
  responsebody.Statistics:
    properties:
      longest_activity:
        type: integer
      minutes_spent:
        type: integer
      user_id:
        type: string
    type: object
  responsebody.Token:
    properties:
      token:
        type: string
    type: object
  responsebody.Workout:
    properties:
      date:
        type: string
      duration:
        type: integer
      id:
        type: string
      kind:
        type: string
    type: object
host: dreik.d.qarwe.online
info:
  contact: {}
  description: API server for yodreik application
  title: yodreik API
  version: "0.1"
paths:
  /activity:
    get:
      consumes:
      - application/json
      description: returns user's workout history
      parameters:
      - description: Begin date
        in: query
        name: begin
        type: string
      - description: End date
        in: query
        name: end
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsebody.ActivityHistory'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsebody.Message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responsebody.Message'
      security:
      - AccessToken: []
      summary: Get user's activity history
      tags:
      - activity
  /auth/account:
    get:
      description: returns an user's information, that currently logged in
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsebody.Account'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responsebody.Message'
      security:
      - AccessToken: []
      summary: Get information about current user
      tags:
      - auth
    patch:
      consumes:
      - application/json
      description: updates user entity in storage
      parameters:
      - description: User Information
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requestbody.UpdateAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsebody.Message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responsebody.Message'
      security:
      - AccessToken: []
      summary: Update personal information
      tags:
      - auth
    post:
      consumes:
      - application/json
      description: create user in database
      parameters:
      - description: User information
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requestbody.CreateAccount'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responsebody.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsebody.Message'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/responsebody.Message'
      summary: Create new account
      tags:
      - auth
  /auth/account/avatar:
    delete:
      description: deletes user's avatar image
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsebody.Account'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsebody.Message'
      security:
      - AccessToken: []
      summary: Delete user avatar
      tags:
      - auth
    patch:
      consumes:
      - multipart/form-data
      description: uploads a new avatar image for the user. Only PNG, JPG, and JPEG
        formats are allowed
      parameters:
      - description: Avatar Image
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsebody.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsebody.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsebody.Message'
      security:
      - AccessToken: []
      summary: Upload User Avatar
      tags:
      - auth
  /auth/account/confirm:
    post:
      consumes:
      - application/json
      description: confirms user's email
      parameters:
      - description: Token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requestbody.ConfirmAccount'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsebody.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsebody.Message'
      summary: Confirm account's email
      tags:
      - auth
  /auth/password:
    patch:
      consumes:
      - application/json
      description: updates password for user
      parameters:
      - description: User information
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requestbody.UpdatePassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsebody.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsebody.Message'
      summary: Update password
      tags:
      - auth
  /auth/password/reset:
    post:
      consumes:
      - application/json
      description: sends an email with recovery link
      parameters:
      - description: User information
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requestbody.ResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsebody.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsebody.Message'
      summary: Request password reset
      tags:
      - auth
  /auth/session:
    post:
      consumes:
      - application/json
      description: check if user exists, and return an access token
      parameters:
      - description: User information
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requestbody.CreateSession'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsebody.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsebody.Message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responsebody.Message'
      summary: Create a session for existing account
      tags:
      - auth
  /healthcheck:
    get:
      consumes:
      - application/json
      description: check if server status is ok
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Ping a server
      tags:
      - status
  /statistics:
    get:
      description: returns user's all-time statistics
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsebody.Statistics'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responsebody.Message'
      security:
      - AccessToken: []
      summary: Get user's statistics
      tags:
      - activity
  /user/{username}:
    get:
      description: returns an user's information and week activity history
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsebody.Profile'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responsebody.Message'
      summary: Get public information about user by username
      tags:
      - user
  /workout:
    post:
      consumes:
      - application/json
      description: creates a new record about workout session
      parameters:
      - description: Information about workout session
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/requestbody.CreateWorkout'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responsebody.Workout'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsebody.Message'
      security:
      - AccessToken: []
      summary: Create a record about past workout
      tags:
      - activity
schemes:
- https
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
