name: Push image to DockerHub

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t jus1d/dreik-api:latest .

      - name: Push Docker image
        run: |
          docker push jus1d/dreik-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Run on remote server
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            docker rmi jus1d/dreik-api
            cd ${{ secrets.PROJECT_DIR }}
            docker compose down
            docker compose up -d
